[versions]

media3Exoplayer = "1.8.0"

agp = "8.13.1"

composeVersion = "1.9.4"

kotlin = "2.2.21"

coreKtx = "1.17.0"

junit = "4.13.2"

#junitVersion = "1.3.0"

#espressoCore = "3.7.0"

lifecycleRuntimeKtx = "2.9.4"

activityCompose = "1.11.0"

composeBom = "2025.11.00"

navigationCompose = "2.9.6"

material3 = "1.4.0"

navigationRuntimeKtx = "2.9.6"

navigationTesting = "2.9.6"

robolectric = "4.16"

roomVersion = "2.8.3"

coreKtxVersion = "1.7.0"

ui = "1.9.4"

# kotlinxSerialization = "1.9.0"

kotlinxSerializationJson = "1.6.3"

kotlinPlugin = "1.9.23"





[libraries]

androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeVersion" }

androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeVersion" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }

androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }

androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "roomVersion" }

junit = { group = "junit", name = "junit", version.ref = "junit" }

#androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }

#androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }

androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }

androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }

androidx-navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "navigationTesting" }

# kotlinx-serialization-json-v160 = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "coreKtxVersion" }

androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "ui" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3Exoplayer" }


[plugins]

android-application = { id = "com.android.application", version.ref = "agp" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }


